links:
  - skeleton_part: 0
    links:
        - id: 0
          name: "TODO_nose_to_chest"
          parent_joint: 0
          child_joint: 1

        - id: 1
          name: "TODO_chest_to_right_shoulder"
          parent_joint: 1
          child_joint: 2

        - id: 2
          name: "right_upper_arm"
          parent_joint: 2
          child_joint: 3

        - id: 3
          name: "right_arm"
          parent_joint: 3
          child_joint: 4

        - id: 4
          name: "TODO_chest_to_left_shoulder"
          parent_joint: 1
          child_joint: 5

        - id: 5
          name: "left_upper_arm"
          parent_joint: 5
          child_joint: 6

        - id: 6
          name: "left_arm"
          parent_joint: 6
          child_joint: 7

        - id: 7
          name: "TODO_chest_to_pelvis"
          parent_joint: 1
          child_joint: 8

        - id: 8
          name: "TODO_pelvis_to_right_hip"
          parent_joint: 8
          child_joint: 9

        - id: 9
          name: "right_thigh"
          parent_joint: 9
          child_joint: 10

        - id: 10
          name: "right_shank"
          parent_joint: 10
          child_joint: 11

        - id: 11
          name: "TODO_right_foot_to_1toe"
          parent_joint: 11
          child_joint: 22

        - id: 12
          name: "TODO_right_1toe_to_5toe"
          parent_joint: 22
          child_joint: 23

        - id: 13
          name: "TODO_right_foot_to_heel"
          parent_joint: 11
          child_joint: 24

        - id: 14
          name: "TODO_pelvis_to_left_hip"
          parent_joint: 8
          child_joint: 12

        - id: 15
          name: "left_thigh"
          parent_joint: 12
          child_joint: 13

        - id: 16
          name: "left_shank"
          parent_joint: 13
          child_joint: 14

        - id: 17
          name: "TODO_left_foot_to_1toe"
          parent_joint: 14
          child_joint: 19

        - id: 18
          name: "TODO_left_1toe_to_5toe"
          parent_joint: 19
          child_joint: 20

        - id: 19
          name: "TODO_left_foot_to_heel"
          parent_joint: 14
          child_joint: 21

        - id: 20
          name: "TODO_nose_to_right_eye"
          parent_joint: 0
          child_joint: 15

        - id: 21
          name: "TODO_right_eye_to_ear"
          parent_joint: 15
          child_joint: 17

        - id: 22
          name: "TODO_nose_to_left_eye"
          parent_joint: 0
          child_joint: 16

        - id: 23
          name: "TODO_left_eye_to_ear"
          parent_joint: 16
          child_joint: 18
